# Generated by Django 4.2.1 on 2023-05-04 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 4, 20, 15, 48, 641230, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
