# Generated by Django 4.2.1 on 2023-05-05 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20230504_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 15, 30, 31, 451931, tzinfo=datetime.timezone.utc)),
        ),
    ]
