version: '3.9'

services:
  
  postgres:
    image: postgis/postgis
    container_name: postgres-1
    env_file:
      - IslandGoApp/IslandGoApp/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - IslandGoApp/IslandGoApp/.env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  web:
    image: islandgodocker
    build: .
    command: python IslandGoApp/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - IslandGoApp/IslandGoApp/.env
volumes:
  postgres_data: {}