# Generated by Django 4.2.1 on 2023-05-05 15:30

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_alter_store_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 5, 5, 15, 30, 31, 465080, tzinfo=datetime.timezone.utc))),
                ('buyer', models.CharField(max_length=100)),
                ('wishmaster', models.CharField(max_length=100)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('FULFILLED', 'FULFILLED')], default='PENDING', max_length=10)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists', to='stores.store')),
            ],
        ),
    ]
